name: mib2
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch=1.4.0
  - cudatoolkit=10.1.243
  - numpy=1.18.1
  - numpy-base=1.18.1
  - pip=20.0.2
  - python=3.8.1
  - pytorch=1.4.0
  - torchvision=0.5.0
  - pip:
    - ipykernel==5.1.4
    - ipython==7.12.0
    - ipython-genutils==0.2.0
    - jupyter-client==5.3.4
    - jupyter-core==4.6.3
    - matplotlib==3.1.3
    - notebook==6.0.3
    - pandas==1.0.1
    - pyyaml==5.3
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - seaborn==0.10.0
    - sklearn==0.0
    - tensorboard==2.1.0
    - tqdm==4.42.1
